version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"

  pyspark-notebook:
    image: jupyter/pyspark-notebook:spark-3.2.1
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      # Configure Spark to use the cluster
      - SPARK_OPTS=--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.1
    volumes:
      - .:/home/jovyan/work
    command: start.sh jupyter lab --NotebookApp.token='' --NotebookApp.password=''
    depends_on:
      - kafka

volumes:
  jupyter_data:
    driver: local
