version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"

  spark:
    image: bitnami/spark:3.5.3
    environment:
      - SPARK_MODE=master
      - SPARK_PACKAGES=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.3
      - SPARK_WORKER_MEMORY=2g   # Allocate more memory
      - SPARK_WORKER_CORES=2     # Allocate more CPU cores
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.5.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark
    ports:
      - "8081:8081"

  jupyter:
    image: jupyter/pyspark-notebook:lab-3.5.3
    depends_on:
      - spark
    environment:
      - SPARK_MASTER=spark://spark:7077
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
