services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./scripts/create-topic.sh:/create-topic.sh
    entrypoint: >
      sh -c "
        /etc/confluent/docker/run & 
        sleep 10; 
        bash /create-topic.sh; 
        wait \$!
      "
    depends_on:
      - zookeeper


  spark-consumer:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-consumer
    depends_on:
      - kafka
    volumes:
      - ./spark:/app
    ports:
      - "4040:4040"

  wiki-producer:
    build:
      context: ./wiki-producer
      dockerfile: Dockerfile
    container_name: wiki-producer
    depends_on:
      - kafka
    volumes:
      - ./wiki-producer:/app
